# Generated by Django 4.0.5 on 2022-06-27 22:43

from django.db import migrations
import pypro32.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pypro32.base.models.UserManager()),
            ],
        ),
    ]
